# Generated by Django 3.2.5 on 2021-07-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databased', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
